# Generated by Django 3.1.5 on 2022-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_abridged',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_full',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
